### ISSUE TITLE
CINIC Dataset is Missing 

### ISSUE THREAD

**Issue by eepLearning** [IdanAchituve/pFedGP#1]
Dear authors
Thank you for sharing source code, the flow of this paper is great and the code is also great.

Could you provide CINIC Dataset  or source code about it?
I wonder Why is that dataset in paper and not in code. I wonder how you implement it.

Thank you for your time!

**Comment by IdanAchituve** [comment]
Hi,
Thank you for the kind comment.
Following your request we uploaded a code for handling heterogeneous_class_dist experiments with CINIC-10 as well.
Note that it is very similar to that of CIFAR-10/100.
In order to use it, you first need to download CINIC-10 from [here](https://github.com/BayesWatch/cinic-10). Then when running the code, point to the location of the data folder using the argument _--data-path_

Cheers,
Idan

**Comment by eepLearning** [comment]
Thank you so much for the quick and kind reply.

I hope everything goes well with you.
Sincerely yours.
